<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="kernel" nsURI="http:///kernel.ecore" nsPrefix="kernel">
  <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
    <details key="originalName" value="Kernel"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DirectedRelationship" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Association"/>
  <eClassifiers xsi:type="ecore:EClass" name="Comment"/>
  <eClassifiers xsi:type="ecore:EClass" name="Dependency"/>
  <eClassifiers xsi:type="ecore:EClass" name="Element" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="owner" ordered="false"
        eType="#//Element" changeable="false" volatile="true" transient="true" derived="true">
      <eAnnotations source="union"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Namespace" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Package"/>
  <eClassifiers xsi:type="ecore:EClass" name="PackageableElement" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Relationship" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Model"/>
  <eClassifiers xsi:type="ecore:EClass" name="Test" eSuperTypes="../../../../org.eclipse.uml2.uml/model/UML.ecore#//Behavior">
    <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
      <details key="originalName" value="TEST"/>
    </eAnnotations>
  </eClassifiers>
  <eSubpackages name="extensions" nsURI="http:///kernel/extensions.ecore" nsPrefix="kernel.extensions">
    <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
      <details key="originalName" value="_Extensions"/>
    </eAnnotations>
    <eSubpackages name="tags" nsURI="http:///kernel/extensions/tags.ecore" nsPrefix="kernel.extensions.tags">
      <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
        <details key="originalName" value="Tags"/>
      </eAnnotations>
      <eClassifiers xsi:type="ecore:EClass" name="Element">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="tag" ordered="false"
            upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="customProperty" ordered="false"
            upperBound="-1" eType="#//extensions/i18n/I18nKeyedString" containment="true">
          <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
            <details key="body" value="owningElement"/>
          </eAnnotations>
        </eStructuralFeatures>
      </eClassifiers>
    </eSubpackages>
    <eSubpackages name="i18n" nsURI="http:///kernel/extensions/i18n.ecore" nsPrefix="kernel.extensions.i18n">
      <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
        <details key="originalName" value="I18N"/>
      </eAnnotations>
      <eClassifiers xsi:type="ecore:EClass" name="I18nBaseString">
        <eOperations name="value" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
          <eParameters name="language" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        </eOperations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="value" ordered="false"
            upperBound="-1" eType="#//extensions/i18n/I18nValue" containment="true">
          <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
            <details key="body" value="owningElement"/>
          </eAnnotations>
        </eStructuralFeatures>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="I18nValue">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="language" ordered="false"
            lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="body" ordered="false"
            lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="I18nDescriptiveElement" abstract="true"
          eSuperTypes="#//extensions/i18n/I18nNamedElement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="purpose" ordered="false"
            eType="#//extensions/i18n/I18nString" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="body" ordered="false"
            eType="#//extensions/i18n/I18nString" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="I18nNamedElement" abstract="true"
          eSuperTypes="#//NamedElement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="displayName" ordered="false"
            eType="#//extensions/i18n/I18nString" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="I18nString" eSuperTypes="#//extensions/i18n/I18nBaseString"/>
      <eClassifiers xsi:type="ecore:EClass" name="Comment">
        <eStructuralFeatures xsi:type="ecore:EReference" name="body" ordered="false"
            eType="#//extensions/i18n/I18nString" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="I18nKeyedString" eSuperTypes="#//extensions/i18n/I18nBaseString">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" ordered="false"
            lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eClassifiers>
    </eSubpackages>
    <eSubpackages name="relationships" nsURI="http:///kernel/extensions/relationships.ecore"
        nsPrefix="kernel.extensions.relationships">
      <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
        <details key="originalName" value="Relationships"/>
      </eAnnotations>
      <eClassifiers xsi:type="ecore:EClass" name="DoNotUseRelationship" abstract="true">
        <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
          <details key="originalName" value="DO_NOT_USE_Relationship"/>
        </eAnnotations>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="DoNotUseRelationshipType" eSuperTypes="#//extensions/i18n/I18nNamedElement">
        <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
          <details key="originalName" value="DO_NOT_USE_RelationshipType"/>
        </eAnnotations>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="SuperseedingRelationship" eSuperTypes="#//DirectedRelationship">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="superseedingType" ordered="false"
            lowerBound="1" eType="#//extensions/relationships/SuperseedingType" defaultValueLiteral="Equal"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="SuperseedingType">
        <eLiterals name="added">
          <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
            <details key="originalName" value="Added"/>
          </eAnnotations>
        </eLiterals>
        <eLiterals name="equal" value="1">
          <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
            <details key="originalName" value="Equal"/>
          </eAnnotations>
        </eLiterals>
        <eLiterals name="updatedMajor" value="2">
          <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
            <details key="originalName" value="UpdatedMajor"/>
          </eAnnotations>
        </eLiterals>
        <eLiterals name="updatedMinor" value="3">
          <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
            <details key="originalName" value="UpdatedMinor"/>
          </eAnnotations>
        </eLiterals>
        <eLiterals name="removed" value="4">
          <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
            <details key="originalName" value="Removed"/>
          </eAnnotations>
        </eLiterals>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Element" abstract="true">
        <eStructuralFeatures xsi:type="ecore:EReference" name="superseedingRelationship"
            ordered="false" upperBound="-1" eType="#//extensions/relationships/SuperseedingRelationship">
          <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
            <details key="body" value="document"/>
          </eAnnotations>
        </eStructuralFeatures>
      </eClassifiers>
    </eSubpackages>
    <eSubpackages name="mof" nsURI="http:///kernel/extensions/mof.ecore" nsPrefix="kernel.extensions.mof">
      <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
        <details key="originalName" value="MOF"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
      </eAnnotations>
      <eClassifiers xsi:type="ecore:EClass" name="Element">
        <eOperations name="model" ordered="false" eType="#//extensions/mof/Model">
          <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
            <details key="body" value="if (owner = null) then&#xD;&#xA;  null&#xD;&#xA;else if (owner.oclIsKindOf(Model)) then&#xD;&#xA;  owner.oclAsType(Model)&#xD;&#xA;else&#xD;&#xA;  owner.model()&#xD;&#xA;endif&#xD;&#xA;endif"/>
          </eAnnotations>
        </eOperations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="model" ordered="false"
            eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject">
          <eAnnotations source="http://schema.omg.org/spec/MOF/2.0/emof.xml#Property.oppositeRoleName">
            <details key="body" value="element"/>
          </eAnnotations>
          <eAnnotations source="subsets" references="#//Element/owner"/>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="uuid" ordered="false"
            lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
            unsettable="true" iD="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Model"/>
    </eSubpackages>
    <eSubpackages name="oid" nsURI="http:///kernel/extensions/oid.ecore" nsPrefix="kernel.extensions.oid">
      <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
        <details key="originalName" value="Oid"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
      </eAnnotations>
      <eClassifiers xsi:type="ecore:EClass" name="Element">
        <eOperations name="oid" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
          <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
            <details key="body" value="uuid"/>
          </eAnnotations>
        </eOperations>
      </eClassifiers>
    </eSubpackages>
  </eSubpackages>
</ecore:EPackage>
