<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="sbom" nsURI="http://schumann.engineering/sbom/1" nsPrefix="sbom">
  <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
    <details key="originalName" value="SBOM"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="DescribedElement" abstract="true" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="summary" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="license" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="supplier" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Element" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reference" ordered="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timestamp" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedProperty" ordered="false"
        upperBound="-1" eType="#//Property" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Property">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" ordered="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Component" eSuperTypes="#//DescribedElement">
    <eOperations name="getSbom" ordered="false" lowerBound="1" eType="#//Sbom"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedComponent" ordered="false"
        upperBound="-1" eType="#//Component" containment="true" eOpposite="#//Component/owner"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owner" ordered="false"
        eType="#//Component" eOpposite="#//Component/ownedComponent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredComponent" ordered="false"
        upperBound="-1" eType="#//Component" eOpposite="#//Component/requiredBy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredBy" ordered="false"
        upperBound="-1" eType="#//Component" eOpposite="#//Component/requiredComponent"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" ordered="false" lowerBound="1"
        eType="#//ComponentType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isSOUP" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="classificationIec81001_5_1"
        ordered="false" lowerBound="1" eType="#//Iec81001_5_1_Classification"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="classificationIec62304"
        ordered="false" eType="#//Iec62304_Classification"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owningSbom" ordered="false"
        eType="#//Sbom"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ComponentType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Specifies the type of component. For software components, classify as application if no more specific appropriate classification is available or cannot be determined for the component."/>
    </eAnnotations>
    <eLiterals name="Application">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A software application. Refer to https://en.wikipedia.org/wiki/Application_software for information about applications."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="DeviceDriver" value="1">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A special type of software that operates or controls a particular type of device. Refer to https://en.wikipedia.org/wiki/Device_driver"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="Device" value="2">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A hardware device such as a processor, or chip-set. A hardware device containing firmware SHOULD include a component for the physical hardware itself, and another component of type 'firmware' or 'operating-system' (whichever is relevant), describing information about the software running on the device.&#xD;&#xA;See also the list of known device properties."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="Library" value="3">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A software library. Refer to https://en.wikipedia.org/wiki/Library_(computing)&#xD;&#xA;for information about libraries. All third-party and open source reusable components will likely be a library. If the library also has key features of a framework, then it should be classified as a framework. If not, or is unknown, then specifying library is RECOMMENDED."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="OperatingSystem" value="4">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A software operating system without regard to deployment model (i.e. installed on physical hardware, virtual machine, image, etc) Refer to https://en.wikipedia.org/wiki/Operating_system"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="Framework" value="5">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A software framework. Refer to https://en.wikipedia.org/wiki/Software_framework for information on how frameworks vary slightly from libraries."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="Container" value="6">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A packaging and/or runtime format, not specific to any particular technology, which isolates software inside the container from software outside of a container through virtualization technology. Refer to https://en.wikipedia.org/wiki/OS-level_virtualization"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="Platform" value="7">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A runtime environment which interprets or executes software. This may include runtimes such as those that execute bytecode or low-code/no-code application platforms."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="Firmware" value="8">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A special type of software that provides low-level control over a devices hardware. Refer to https://en.wikipedia.org/wiki/Firmware"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="File" value="9">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A computer file. Refer to https://en.wikipedia.org/wiki/Computer_file for information about files."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="MachineLearningModel" value="10">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A model based on training data that can make predictions or decisions without being explicitly programmed to do so."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="Data" value="11">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A collection of discrete values that convey information."/>
      </eAnnotations>
    </eLiterals>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Iec81001_5_1_Classification">
    <eLiterals name="MAINTAINED"/>
    <eLiterals name="SUPPORTED" value="1"/>
    <eLiterals name="REQUIRED" value="2"/>
    <eLiterals name="NotApplicable" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Iec62304_Classification">
    <eLiterals name="C"/>
    <eLiterals name="B" value="1"/>
    <eLiterals name="A" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sbom" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedRelationship" ordered="false"
        upperBound="-1" eType="#//Relationship" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedComponent" ordered="false"
        lowerBound="1" upperBound="-1" eType="#//Component" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Relationship">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" ordered="false"
        lowerBound="1" eType="#//NamedElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" ordered="false"
        lowerBound="1" eType="#//NamedElement"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" ordered="false" lowerBound="1"
        eType="#//RelationshipType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RelationshipType">
    <eLiterals name="Unknown"/>
    <eLiterals name="contains" value="1"/>
    <eLiterals name="isContainedBy" value="2"/>
    <eLiterals name="requires" value="3"/>
    <eLiterals name="isRequiredBy" value="4"/>
    <eLiterals name="runsOn" value="5"/>
    <eLiterals name="runs" value="6"/>
    <eLiterals name="describes" value="7"/>
    <eLiterals name="isDescribedBy" value="8"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MetadataLibrary">
    <eStructuralFeatures xsi:type="ecore:EReference" name="artifactMeta" ordered="false"
        upperBound="-1" eType="#//ArtifactMetadata" containment="true" eOpposite="#//ArtifactMetadata/library"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="supplierMeta" ordered="false"
        upperBound="-1" eType="#//SupplierMetadata" containment="true" eOpposite="#//SupplierMetadata/library"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArtifactMetadata" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="supplier" ordered="false"
        lowerBound="1" eType="#//SupplierMetadata" eOpposite="#//SupplierMetadata/component"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="library" ordered="false"
        lowerBound="1" eType="#//MetadataLibrary" eOpposite="#//MetadataLibrary/artifactMeta"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SupplierMetadata" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="library" ordered="false"
        lowerBound="1" eType="#//MetadataLibrary" eOpposite="#//MetadataLibrary/supplierMeta"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="component" ordered="false"
        upperBound="-1" eType="#//ArtifactMetadata" eOpposite="#//ArtifactMetadata/supplier"/>
  </eClassifiers>
</ecore:EPackage>
