<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="sbom" nsURI="http://schumann.engineering/sbom/1" nsPrefix="sbom">
  <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
    <details key="originalName" value="SBOM"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Component" eSuperTypes="#//Namespace"/>
  <eClassifiers xsi:type="ecore:EClass" name="Namespace" abstract="true" eSuperTypes="#//DescribedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedComponent" ordered="false"
        upperBound="-1" eType="#//Component" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredComponent" ordered="false"
        upperBound="-1" eType="#//Component"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedProperty" ordered="false"
        upperBound="-1" eType="#//Propety" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" ordered="false" lowerBound="1"
        eType="#//NamespaceType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isSOUP" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DescribedElement" abstract="true" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="summary" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="license" ordered="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="supplier" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Element" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reference" ordered="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timestamp" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Propety">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" ordered="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="NamespaceType">
    <eLiterals name="Application"/>
    <eLiterals name="Firmware" value="1"/>
    <eLiterals name="Hardware" value="2"/>
    <eLiterals name="Library" value="3"/>
    <eLiterals name="OperatingSystem" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Relationship">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" ordered="false"
        lowerBound="1" eType="#//NamedElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" ordered="false"
        lowerBound="1" eType="#//NamedElement"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" ordered="false" lowerBound="1"
        eType="#//RelationshipType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RelationshipType">
    <eLiterals name="Unknown"/>
    <eLiterals name="contains" value="1"/>
    <eLiterals name="isContainedBy" value="2"/>
    <eLiterals name="requires" value="3"/>
    <eLiterals name="isRequiredBy" value="4"/>
    <eLiterals name="runsOn" value="5"/>
    <eLiterals name="runs" value="6"/>
    <eLiterals name="describes" value="7"/>
    <eLiterals name="isDescribedBy" value="8"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sbom" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedSystem" ordered="false"
        lowerBound="1" upperBound="-1" eType="#//System" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedRelationship" ordered="false"
        upperBound="-1" eType="#//Relationship" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="System" eSuperTypes="#//Namespace"/>
</ecore:EPackage>
